"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

if os.getenv("GOOGLE_API_KEY") and os.getenv("GEMINI_API_KEY"):
    os.environ.pop("GEMINI_API_KEY", None)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-x^h*)0tv^-l1+l)=^j)g8$wf*p8wm$qy@vg&bn6+ifzr5*d88y",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "analytics",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "analytics.cors.LocalCorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


def database_config_from_url(url: str) -> dict[str, object]:
    parsed = urlparse(url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        raise ValueError(f"Unsupported DATABASE_URL scheme: {parsed.scheme}")

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": parsed.path.lstrip("/"),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
    }


DATABASE_URL = os.getenv("DATABASE_URL", "")
if DATABASE_URL:
    DATABASES = {"default": database_config_from_url(DATABASE_URL)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ANALYTICS_DATABASE_URL = os.getenv("ANALYTICS_DATABASE_URL", "")
ANALYTICS_DATABASE_DIALECT = os.getenv("ANALYTICS_DATABASE_DIALECT", "postgres")
ANALYTICS_SQL_TIMEOUT_SECONDS = int(os.getenv("ANALYTICS_SQL_TIMEOUT_SECONDS", "30"))
ANALYTICS_SQL_MAX_ROWS = int(os.getenv("ANALYTICS_SQL_MAX_ROWS", "200"))
ANALYTICS_SQL_MAX_CHARS = int(os.getenv("ANALYTICS_SQL_MAX_CHARS", "12000"))
ANALYTICS_AGENT_MAX_STEPS = int(os.getenv("ANALYTICS_AGENT_MAX_STEPS", "20"))

ANALYTICS_LLM_MODEL = os.getenv("ANALYTICS_LLM_MODEL", "gemini-3.1-flash-lite")
ANALYTICS_LLM_PROVIDER_MODEL = os.getenv(
    "ANALYTICS_LLM_PROVIDER_MODEL",
    f"google_genai:{ANALYTICS_LLM_MODEL}",
)

MEMORY_API_BASE_URL = os.getenv("MEMORY_API_BASE_URL", "")
MEMORY_PROJECT = os.getenv("MEMORY_PROJECT", "sqlanalytics")
MEMORY_TIMEOUT_SECONDS = float(os.getenv("MEMORY_TIMEOUT_SECONDS", "10"))

LANGFUSE_PUBLIC_KEY = os.getenv("LANGFUSE_PUBLIC_KEY", "").strip("\"'")
LANGFUSE_SECRET_KEY = os.getenv("LANGFUSE_SECRET_KEY", "").strip("\"'")
LANGFUSE_HOST = (
    os.getenv("LANGFUSE_HOST")
    or os.getenv("LANGFUSE_BASE_URL")
    or "https://cloud.langfuse.com"
).strip("\"'")
LANGFUSE_TRACE_LANGCHAIN_INTERNALS = (
    os.getenv("LANGFUSE_TRACE_LANGCHAIN_INTERNALS", "false").lower() == "true"
)

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://127.0.0.1:8080,http://localhost:8080,"
        "http://127.0.0.1:8001,http://localhost:8001",
    ).split(",")
    if origin.strip()
]

# Redis
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")
REPORT_STREAM_REDIS_URL = os.getenv("REPORT_STREAM_REDIS_URL", REDIS_URL)

# Celery
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_TASK_DEFAULT_QUEUE = os.getenv("CELERY_TASK_DEFAULT_QUEUE", "sqlanalytics")
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Event streaming (Redis Streams bridge between worker and view)
REPORT_STREAM_BLOCK_MS = int(os.getenv("REPORT_STREAM_BLOCK_MS", "5000"))
REPORT_STREAM_TIMEOUT_SECONDS = int(os.getenv("REPORT_STREAM_TIMEOUT_SECONDS", "120"))
REPORT_STREAM_TTL_SECONDS = int(os.getenv("REPORT_STREAM_TTL_SECONDS", "300"))
REPORT_STREAM_SOCKET_TIMEOUT_SECONDS = float(
    os.getenv(
        "REPORT_STREAM_SOCKET_TIMEOUT_SECONDS",
        str(max((REPORT_STREAM_BLOCK_MS / 1000) + 5, 10)),
    )
)
